### ISSUE TITLE
[chore] codeRabbit Ai 코드 리뷰가 main외의 develop 브랜치로 push할 때도 리뷰를 달도록 수정하기

### ISSUE THREAD

**Issue by badaclockA** [byulhook/byul#43]
### 📄 Description

- 현재 develop 브랜치가 base일 때는 AI 코드리뷰가 비활성화 되어 있음.
```
Auto reviews are disabled on base/target branches other than the default branch. Please check the settings in the CodeRabbit UI or the .coderabbit.yaml file in this repository. To trigger a single review, invoke the @coderabbitai review command. You can disable this status message by setting the reviews.review_status to false in the CodeRabbit configuration file.
기본 브랜치 이외의 베이스/타겟 브랜치에서는 자동 리뷰가 비활성화되어 있습니다. CodeRabbit UI 또는 이 저장소의 .coderabbit.yaml 파일에서 설정을 확인하세요. 단일 리뷰를 트리거하려면 @coderabbitai review 명령어를 호출하세요. CodeRabbit 설정 파일에서 reviews.review_status를 false로 설정하여 이 상태 메시지를 비활성화할 수 있습니다.
```

- codeRabbit Ai 코드 리뷰가 main외의 develop 브랜치로 push할 때도 리뷰를 달도록 설정할 예정임.
- PR 제목에 WIP가 붙은 것은 코드 리뷰 무시하도록 설정할 예정임.

### ✅ Tasks

- [ ]  .coderabbit.yaml 를 수정

### 📝 Notes

```
# CodeRabbit configuration
version: 1
reviews:
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    base_branches:
      - "main"
      - "develop"
      - "release/*"
  ```
